development:
  server: "http://54.200.130.27:9292/faye/faye"
  secret_token: "secret"
test:
  server: "http://54.200.130.27:9292/faye/faye"
  secret_token: "secret"
production:
  server: "http://54.200.130.27:9292/faye/faye"
  secret_token: <%= ENV["SOCKET_TOKEN"] %>
  signature_expiration: 3600 # one hour
