source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'
#gem 'spring',        group: :development
gem 'devise'

gem 'jquery-rails'
gem "private_pub"
gem "thin"
gem "encryptor"